version: '3'

services:
  strapi:
    build:
      context: ./docker/strapi
      dockerfile: Dockerfile
    environment:
      - PORT=1337
      - ADMIN_JWT_SECRET=d1137b800b43ec78d42b6446ecbb2f78
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
    ports:
      - 1337:1337
    working_dir: /opt/app
    volumes:
      - ./app:/opt/app
    depends_on:
      - db

  db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=strapi
    ports:
      - 27017:27017
    volumes:
      - ./.db:/data/db
    restart: always

volumes:
  .db:
