version: '3'

services:
  strapi:
    build:
      context: .
      dockerfile: ./docker/strapi/Dockerfile.local
    environment:
      - DATABASE_CLIENT=mysql
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=strapi
    ports:
      - 1337:1337
    working_dir: /opt/app
    volumes:
      - ./app:/opt/app
      - node_modules:/opt/app/node_modules
    depends_on:
      - db
    networks:
      - gatsby_network

  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    restart: always
    environment:
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
      MYSQL_ROOT_PASSWORD: strapi
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - gatsby_network

networks:
  gatsby_network:
    external: true

volumes:
  node_modules:
  db-data:
